### ISSUE TITLE
Day-3:  Create footer section

### ISSUE THREAD

**Issue by ashitashahu** [imrayn06/Microsoft-Mavericks_054#14]
- [x] Add sections for Products, support, warranty and corporate
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/117708398/0e95cb2f-013f-49bf-932e-4de9d3d46eae)

- [x] Add social media icons
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/117708398/da5063db-0a93-49de-b9ff-6d63b366e398)

- [x] Add copyright section
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/117708398/1b23b404-7fb3-4191-8dde-d73b57be5950)

**Comment by Annndyyyy** [comment]
1. Footer Section Done

**Comment by rpriyadarshy** [comment]
Footer Section Done.
