### ISSUE TITLE
Day1- Create mid-section navigation for watch categories.

### ISSUE THREAD

**Issue by imrayn06** [imrayn06/Microsoft-Mavericks_054#2]
- [x] Create mid nav as per img.
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/2fcba44b-82f6-4d17-804d-65fe76f55262)

- [x] add the links :-
    G-SHOCK Brand Site
    Store Search
    Support
    Services V
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/2fcba44b-82f6-4d17-804d-65fe76f55262)

- [x] Create mid-section navigation for watch categories.
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/3b5926c4-ed0b-4b16-8fb5-9c2f35f200d4)
![Uploading image.png…]()
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/304fdc38-5c4b-429b-a346-f477cc0c5e26)

**Comment by imrayn06** [comment]
Tasks for Day1 has been updated.

**Comment by ashitashahu** [comment]
first mid-section navbar made

**Comment by ashitashahu** [comment]
1. added the first mid-navbar and logo
2. added the menu bar

![Image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/117708398/331301a4-4fc7-451d-8ada-019e5bda60ef)
