### ISSUE TITLE
Day1-Create footer section.

### ISSUE THREAD

**Issue by imrayn06** [imrayn06/Microsoft-Mavericks_054#3]
- [x] [Create this small nav over footer section ] 
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/dab75e79-48a1-43dd-9a49-a07be071291b)
 

- [ ] add options as in img to choose from.
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/1ce8602e-856a-416e-9c02-b30d56f6b728)

- [ ] add social media logos
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/e34421b7-6d01-4e97-bd1b-5f4e15d98cfd)

- [ ] add the further details..
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/3af28ef0-20d8-43fd-9170-230e66ad1a14)

- [ ] add reachout section.
![image](https://github.com/imrayn06/Microsoft-Mavericks_054/assets/66328938/ccbaa829-5f01-4ebd-92e4-489a2f8e481b)

**Comment by imrayn06** [comment]
Tasks have been updated.

**Comment by Annndyyyy** [comment]
1. created the html code 
2. created the style.css
